version: "2"
services:
  cassandra:
    image: cassandra
    restart: on-failure
    ports:
      - 9042:9042
      - 9160:9160
    volumes:
      - ~/Training/volumes/cassandra:/var/lib/cassandra
  jenkins:
    image: jenkins
    restart: on-failure
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home
  mongo:
    image: mongo
    restart: on-failure    
    ports:
      - 27017:27017
    volumes:
      - ~/Training/volumes/mongo:/data/db  
  neo4j:
    image: neo4j
    restart: on-failure
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - ~/Training/volumes/neo4j/data:/data
  redis:
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ~/Training/volumes/redis:/data
